---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoExpress-deployment
  labels:
    app: mongo-express
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-express-secret
              key: mongo-express-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-express-secret
              key: mongo-express-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongo-configmap
              key: database_url
          
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
type: Opaque
data:
  mongo-express-username: bW9uZ29hZG1pbg==
  mongo-express-password: c2VjcmV0

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
