---
apiVersion: apps/v1
kind: Deployment
metadate:
  name: nginx-deployment2
  labels:
    app: nginx
  namespace: rp1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
